package com.example.leanon.navigation

const val ROUTE_SIGNUP = "signup"
const val ROUTE_LOGIN = "login"
//const val ROUTE_HOME = "home_screen"
const val ROUTE_ADD_POST = "add_post_screen"
//const val ROUTE_BIBLE = "bible_screen"
//const val ROUTE_BOOKS = "books"
//const val ROUTE_CHURCH = "church_screen"
//const val ROUTE_NOTEPAD = "notepad_screen"
const val ROUTE_PRAYER_NOTEPAD = "prayer_notepad"
const val ROUTE_SERMON_NOTEPAD = "sermon_notepad"
const val ROUTE_BIBLE_STUDY_NOTEPAD = "bible_study_notepad"
const val ROUTE_ADD_PRAYER = "add_prayer_screen"
const val ROUTE_ADD_SERMON = "add_sermon_screen"
const val ROUTE_ADD_BIBLE_STUDY= "add_bible_study_screen"
const val ROUTE_PROFILE = "profile_screen"
